name: smart_receipt_tracker
description: "Công cụ theo dõi chi phí và phân tích hóa đơn bằng OCR trên Flutter & Dart với CustomPainter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  
  # Camera & Image
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  path_provider: ^2.1.2
  path: ^1.9.0

  # On-device ML Kit OCR
  google_mlkit_text_recognition: ^0.11.0

  # Local Database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  shared_preferences: ^2.2.2

  # Firebase Cloud Database & Storage
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample_receipts/
